version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker_compose/app/Dockerfile
    image: remote-ph-app
    container_name: remote-ph-app
    restart: unless-stopped
    tty: true
    expose:
      - "8080"
    volumes:
      - ./web:/var/www/app
    env_file:
      - ./docker_compose/app/.env
      - ./docker_compose/mongodb/.env
      - ./docker_compose/postgres/.env
    environment:
      DEBUG: 'true'
      APP_NAME: 'FlaskApp'
    # command: gunicorn --reload wsgi:app -w 1 -b 0.0.0.0:8080
    networks:
      - remote-ph-network

  nginx:
    image: nginx:alpine
    container_name: remote-ph-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker_compose/nginx/conf.d/:/etc/nginx/conf.d/
    env_file:
      - ./docker_compose/nginx/.env
    environment:
      SERVICE_NAME: mongodb
      SERVICE_TAGS: dev
    networks:
      - remote-ph-network

  postgres:
    build: ./docker_compose/postgres/
    image: remote-ph-postgres
    container_name: remote-ph-postgres
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./docker_compose/postgres/.env
    environment:
      SERVICE_NAME: postgres
      SERVICE_TAGS: dev
    networks:
      - remote-ph-network

  mongodb:
    image: mongo:4.0.8
    container_name: remote-ph-mongo
    restart: unless-stopped
    tty: true
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    env_file:
      - ./docker_compose/mongodb/.env
    command: mongod --auth
    networks:
      - remote-ph-network


networks:
  remote-ph-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
  mongodbdata:
    driver: local
